Port to GLib
sugarlabs/across-and-down-activity pull request #6
Opened 2018-10-30 17:57 UTC by aryanharitsh123

Working(Tested By Hrishi).

2018-10-30 18:12 UTC, rhl-bthr requested changes
Also, please also squash your commits into one. The current commit messages are not descriptive of the changes you are making. See our guide to writing commits: https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits

The PR is also not linked to the issue being solved.

2018-10-30 18:12 UTC, pro-panda commented on sugargame/canvas.py
> -from gi.repository import GLib
Why is this import removed ?

2018-10-30 18:12 UTC, pro-panda commented on sugargame/event.py
>  from gi.repository import GObject
Please remove this import, as suggested in #5 review

2018-10-30 18:15 UTC, pro-panda commented
@aryanharitsh123, if someone else has tested your commits, please include them in the `tested-by` section. It makes it easier for other developers to look up.

Also, the activity doesn't work for me due to the missing import. It is strange that it worked for you / Hrishi

2018-10-30 23:38 UTC, quozl commented
Thanks.  Good try.  Was it a trap?  :grin:  @aryanharitsh123, also;
* files in the _sugargame_ directory are from the upstream project https://github.com/sugarlabs/sugargame, and we try to keep them synchronised so that patches can be ported between repositories as needed,
* my method would be to grab the commit from upstream project https://github.com/sugarlabs/sugargame/commit/6d83a59c917f1d05eb0d67027aa453276855480d and apply it here; e.g. `git format-patch` in that repository, then `git am file.patch` in this repository, that way the same code continues to be used and the credit for the change suitably recorded,
* if the commit doesn't apply due to conflicts, there may be earlier commits to apply,
* but the above is best done with the command line interface to `git`, and your commit messages suggest you've been using the GitHub editor; seems easier, but has consequences.

2018-10-31 07:22 UTC, quozl commented
New pull request #8 by same author without closing this one, so I'll close this one.  Next time just force push your branch, it's much easier for everyone.

2018-10-31 07:22 UTC, closed without merging